### ISSUE TITLE
Code from Episode 13: MVVM Helpers is missing

### ISSUE THREAD

**Issue by rarrarrarr** [jamesmontemagno/TheXamarinShow#1]
Will you please upload the monkeys app you showed in [episode 13](https://channel9.msdn.com/Shows/XamarinShow/The-Xamarin-Show-12-MVVM-Helpers)?

I'm excited to get started using your nuget library and would love to be able to use your existing code as a jumping-off point.

Thanks for doing the show and sharing the code.  Keep it up!

**Comment by Leojet86** [comment]
Also looking for this

**Comment by lsaudon** [comment]
I think it's this repo. 
https://github.com/jamesmontemagno/Xamarin.Forms-Monkeys/tree/function-monkeys

**Comment by rarrarrarr** [comment]
Nice, @lsaudon!  Closing the issue.
