### ISSUE TITLE
Binding doesn't work on iOS?

### ISSUE THREAD

**Issue by whitewabbit** [jamesmontemagno/TheXamarinShow#4]
I tried binding on button to navigate. it worked on Android but not in iOS. Please Help.
this is my in my ViewModel
`
public LoginViewModel(INavigation navigation)
        {
            Navigation = navigation;
            SignUpBtnClicked = new Command(async () => await SignUp());
        }

        public INavigation Navigation { get; set; }
        public Command SignUpBtnClicked { get; }

        public async Task SignUp()
        {
            await Navigation.PushAsync(new UserOptionPage());
        }

        #region INotifyPropertyChanged 
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
`

**Comment by jamesmontemagno** [comment]
Is this in my source code somewhere? You probably want to ask on http://forums.xamarin.com
